//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dota2Nube.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dota2NubeConn1 : DbContext
    {
        public Dota2NubeConn1()
            : base("name=Dota2NubeConn1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<GameResult> GameResult { get; set; }
        public virtual DbSet<Pool> Pool { get; set; }
        public virtual DbSet<PoolUsers> PoolUsers { get; set; }
        public virtual DbSet<Prediction> Prediction { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Tournament> Tournament { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserStat> UserStat { get; set; }
    }
}
