//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dota2Nube.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pool()
        {
            this.PoolUsers = new HashSet<PoolUsers>();
        }
    
        public int PoolId { get; set; }
        public string PoolName { get; set; }
        public int TournamentId { get; set; }
        public int UserId { get; set; }
    
        public virtual Tournament Tournament { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PoolUsers> PoolUsers { get; set; }
    }
}
